# 실행에서 제외할 룰 식별자
disabled_rules:
  - trailing_whitespace
  - identifier_name
  
# 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
#included:
#  - Source

# 린트 과정에서 무시할 파일. included 보다 우선순위
excluded:
  - Pods

# Customized Configurable Rules
line_length: 200
